const data = [
    "Apple",
    "apple",
    "APPLE",
    "  Apple",
    "Apple  ",
    "AppLe Pie",
    "Application",
    "Apply",
    "App",
    "app",
    "Banana",
    "banana",
    "BANANA",
    "Banana Split",
    "Blue-berry",
    "Blue berry",
    "Blueberry",
    "Blackberry",
    "Black berry",
    "Cherry",
    "Cherry!",
    "Cherry#1",
    "Cherry123",
    "123Cherry",
    "Mango",
    "mango shake",
    "MangoShake",
    "MANGO",
    "Orange",
    "orange juice",
    "OrangeJuice",
    "Grape",
    "Grapes",
    "Grape Fruit",
    "grapefruit",
    " Pineapple",
    "Pineapple ",
    "PINEAPPLE",
    "Kiwi",
    "kiwi",
    "Kiwifruit",
    "Dragon fruit",
    "Dragonfruit",
    "dragonFruit",
    "Durian",
    "Fig",
    "   ",
    "",
    "  Mango  ",
    "Lemon",
    "leMon",
    "LÉMON",
    "Café",
    "Cafe",
    "Résumé",
    "Resume",
    "naïve",
    "Naive",
    "São Paulo",
    "Sao Paulo",
    "Zebra",
    "Zebra1",
    "Zebra_One",
    "Zebra-One",
    "Zebra One",
    "Alpha",
    "alpha",
    "ALPHA",
    "Alpha1",
    "Alpha 1",
    "Beta",
    "beta",
    "Gamma",
    "gamma-ray",
    "Delta",
    "delta force",
    "Echo",
    "echo123",
    "Foxtrot",
    "Golf",
    "Hotel",
    "India",
    "india",
    "Juliet",
    "Kilo",
    "Lima",
    "Mike",
    "November",
    "Oscar",
    "Papa",
    "Quebec",
    "Romeo",
    "Sierra",
    "Tango",
    "Uniform",
    "Victor",
    "Whiskey",
    "X-ray",
    "Yankee",
    "Zulu"
];

document.querySelector("input").addEventListener("input", () => {

    let inputText = document.getElementById("#inputtext").innerText
    let inputArray = inputText.split("")
    console.log(inputArray)
})
